### ISSUE TITLE
Removing inheretance from TwoWire removes stream functionality

### ISSUE THREAD

**Issue by SRGDamia1** [Testato/SoftwareWire#33]
Without inheriting from TwoWire and, in turn from Stream, you lose all stream-like functionality - particularly the parseInt/parseFloat functions and the ability to use SoftwareWire as a drop-in stream instance.

I would appreciate the return of the inheritance.

**Comment by Testato** [comment]
we have decided to remove this inheritance.  read here for the reasons
https://github.com/Testato/SoftwareWire/pull/32
